let StaffData =
[
	{ "EmployeeID": "1"
	, "FirstName": "Jon"
	, "LastName": "Wilson"
	, "Name": "Jon Wilson"
	, "LegalFirstName": "Jon"
	, "Mobile": "8285550000"
	, "OfficePhone": "8285551111"
	, "Extension": "x1337"
	, "Department": "120"
	, "DepartmentName": "IT"
	, "JobCode": "17"
	, "JobTitle": "Developer"
	, "Pager": ""
	, "Email": "jon.wilson@mycom.com"
	, "StreetAddress": "60201 Walnut St."
	, "City": "Asheville"
	, "State": "NC"
	, "PostalCode": "28801"
	, "FileName": "pic.jpg"
	, "SupervisorID": "1"
	},
	{ "EmployeeID": "1"
	, "FirstName": "Joe"
	, "LastName": "Barbon"
	, "Name": "Joe Barbon"
	, "LegalFirstName": "Joe"
	, "Mobile": "8285550001"
	, "OfficePhone": "8285551112"
	, "Extension": "x1338"
	, "Department": "120"
	, "DepartmentName": "IT"
	, "JobCode": "17"
	, "JobTitle": "Jr. Developer"
	, "Pager": ""
	, "Email": "joe.barbon@mycom.com"
	, "StreetAddress": "60201 Walnut St."
	, "City": "Asheville"
	, "State": "NC"
	, "PostalCode": "28801"
	, "FileName": "pic.jpg"
	, "SupervisorID": "1"
	},	
	{ "EmployeeID": "3"
	, "FirstName": "Ray"
	, "LastName": "Carbon"
	, "Name": "Ray Carbon"
	, "LegalFirstName": "Raymond"
	, "Mobile": "8285550002"
	, "OfficePhone": "8285551113"
	, "Extension": "x1339"
	, "Department": "120"
	, "DepartmentName": "IT"
	, "JobCode": "17"
	, "JobTitle": "Database Admin"
	, "Pager": ""
	, "Email": "Ray.Carbon@mycom.com"
	, "StreetAddress": "60201 Walnut St."
	, "City": "Asheville"
	, "State": "NC"
	, "PostalCode": "28801"
	, "FileName": "pic.jpg"
	, "SupervisorID": "1"
	},
]
export default StaffData; 